### ISSUE TITLE
Documentation for Multifield

### ISSUE THREAD

**Issue by joekukish** [Adobe-Consulting-Services/adobe-consulting-services.github.io#141] opened 2019-01-30 13:20 UTC
The Multifield documentation should mention that the NODE_STORE is not compatible with the composite mode. In reality after AEM 6.3, there is no need to keep using the Mulfield from ACS Commons.

**Comment by justinedelson** [comment] 2019-01-30 13:22
FWIW, documentation for this clearly says to not use it: https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/multifield-extension/index.html

@joekukish are you suggesting that this warning be enhanced in some specific way?

**Comment by andrewmkhoury** [comment] 2019-01-30 19:42
@joekukish The problem is that customers already using the ACS commons one, the data gets stored differently, switching to the OOTB one thereafter is expensive.  It would be nice if we offered a conversion tool / script.

**Comment by badvision** [comment] 2020-01-13 14:17
The multifield widget is deprecated and I agree a conversion tool in the code side of things might be helpful but that's not a documentation concern.  I'm closing this for now.

**Closed by badvision** 2020-01-13 14:17 UTC
